### ISSUE TITLE
Support of tlx for nested structure network

### ISSUE THREAD

**Issue by qiutzh** [tensorlayer/TensorLayerX#29]
### New Issue Checklist

- [ ] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

请问，tensorlayerx 目前支持 paddle 做后端，然后运行包含嵌套结构关系的网络模型吗？我运行 tlx 提供的 example 例子，发现 nested_usage_of_layer.py 这个文件以 tf 做后端可以运行，但改成 paddle 做后端，会提示报错，错误提示：

```python
Traceback (most recent call last):
  File "D:/ProjectByPython/code/reference/DL_Platform/TensorLayer/TensorLayerX-0.5.6/examples/basic_tutorials/nested_usage_of_layer.py", line 159, in <module>
    grad = tape.gradient(_loss_ce, train_weights)
  File "D:\Software\miniconda3\envs\py37env_tlx\lib\site-packages\tensorflow_core\python\eager\backprop.py", line 984, in gradient
    if not t.dtype.is_floating:
AttributeError: 'paddle.fluid.core_avx.VarType' object has no attribute 'is_floating'
```

### Reproducible Code

python: 3.7
paddlepaddle version: 2.3.0
tensorlayerx version: 0.5.6

代码就是例子中的 nested_usage_of_layer.py 这个文件。
[nested_usage_of_layer.txt](https://github.com/tensorlayer/TensorLayerX/files/9775292/nested_usage_of_layer.txt)

自己在转换其它存在嵌套关系的网络模型时，如 resnet 时，发现以 paddle 做后端也可以成功运行，但是结果不准确（BatchNorm2d 这一层开始的输出就不再一样了）。

**Comment by Laicheng0830** [comment]
这个报错是正常的，nested_usage_of_layer.py 的代码是混合TF运行的，其中用到了tf.GradientTape()。

**Comment by Laicheng0830** [comment]
[qiutzh](https://github.com/qiutzh)结果不准确能给个github仓链接吗，或者贴例子

**Comment by qiutzh** [comment]
@qiutzh 好的 我整理下发您文件，稍后建个仓库

**Comment by qiutzh** [comment]
@Laicheng0830 两个模型定义文件：
[tlx_vgg.txt](https://github.com/tensorlayer/TensorLayerX/files/9775541/tlx_vgg.txt)
[pd_resnet.txt](https://github.com/tensorlayer/TensorLayerX/files/9775542/pd_resnet.txt)

预测函数：
```python
# coding: utf-8
import os
os.environ['TL_BACKEND'] = 'paddle'
import numpy as np
from utils.load_image import load_image_pd, load_image_tlx

def predict_single_pd(model, image_file):
    """ paddlepaddle single sample prediction """
    import paddle

    print('Model name:', f'{model.__class__.__name__}')
    # img = paddle.rand([1, 3, 224, 224])
    img = load_image_pd(image_file)
    print('Input shape:', img.shape)
    out = model(img)

    # probs = np.array(out[0])
    if isinstance(out, paddle.Tensor):
        probs = paddle.nn.Softmax()(out[0]).numpy()
    elif isinstance(out, list):
        probs = paddle.nn.Softmax()(out[0])[0].numpy()
    preds = (np.argsort(probs)[::-1])[0:5]
    file_path = 'images/imagenet_classes.txt'
    with open(file_path) as f:
        class_names = [line.strip() for line in f.readlines()]
    print('Predicted category:', class_names[np.argmax(out[0])])
    for p in preds:
        print(class_names[p], probs[p])


def predict_single_tlx(model, image_file):
    """ tensorlayerx single sample prediction """
    import paddle
    import tensorlayerx as tlx

    print('Model name:', f'{model.__class__.__name__}')
    # print trainable weights
    # for w in model.trainable_weights:
    #     print(w.name, w.shape)

    img = load_image_tlx(image_file)
    out = model(img)
    if isinstance(out, paddle.Tensor):  # TODO - replace it
        probs = tlx.ops.softmax(out[0]).numpy()
    elif isinstance(out, list):
        probs = tlx.ops.softmax(out[0])[0].numpy()
    preds = (np.argsort(probs)[::-1])[0:5]

    file_path = 'images/imagenet_classes.txt'
    with open(file_path) as f:
        class_names = [line.strip() for line in f.readlines()]
    print('Predicted category:', class_names[np.argmax(out[0])])
    for p in preds:
        print(class_names[p], probs[p])
```

加载图像：
```python
def load_image_pd(image_path):
    """ data format: nchw """
    from paddle import to_tensor

    img = Image.open(image_path).convert('RGB')
    img = img.resize((224, 224), Image.ANTIALIAS)
    img = np.array(img).astype(np.float32)
    img = img.transpose((2, 0, 1))  # CHW
    # img = img[(2, 1, 0), :, :]  # BGR
    img = np.expand_dims(img, 0)
    # # img = img.flatten()
    img = img / 255.0
    img = to_tensor(img)
    return img


def load_image_tlx(image_path):
    """ data_format: nchw """
    import tensorlayerx as tlx

    img = Image.open(image_path).convert('RGB')
    img = img.resize((224, 224), Image.ANTIALIAS)
    img = np.array(img).astype(np.float32)
    img = np.expand_dims(img, 0)
    # img = img.flatten()
    img = img / 255.0
    # img = to_tensor(img)
    img = tlx.convert_to_tensor(img)
    img = tlx.ops.nhwc_to_nchw(img)

    # img = tlx.vision.load_image(image_path)
    # img = tlx.vision.transforms.Resize((224, 224))(img).astype(np.float32) / 255
    # img = paddle.unsqueeze(paddle.Tensor(img), 0)
    # # print('img shape[nhwc]:', img.shape)
    # img = tlx.ops.nhwc_to_nchw(img)
    # # print('img shape[hchw]:', img.shape)

    return img
```

测试：
```python
    def test_resnet(self):
        from models.vision.pd_resnet import resnet18, resnet34, resnet50, resnet101, resnet152

        image_file = "images/dog.jpeg"
        # model = resnet18(pretrained=True)
        # model.eval()
        # predict_single_pd(model, image_file)

        # model = resnet34(pretrained=True)
        # model.eval()
        # predict_single_pd(model, image_file)

        model = resnet50(pretrained=True)
        model.eval()
        predict_single_pd(model, image_file)

        # model = resnet101(pretrained=True)
        # model.eval()
        # predict_single_pd(model, image_file)
        #
        # model = resnet152(pretrained=True)
        # model.eval()
        # predict_single_pd(model, image_file)


        ##########################################################
        from models.vision.tlx_resnet import resnet18, resnet34, resnet50, resnet101, resnet152

        image_file = "images/dog.jpeg"
        # model = resnet18(pretrained=True)
        # model.set_eval()
        # predict_single_tlx(model, image_file)

        # model = resnet34(pretrained=True)
        # model.set_eval()
        # predict_single_tlx(model, image_file)

        model = resnet50(pretrained=True)
        model.set_eval()
        predict_single_tlx(model, image_file)

        # model = resnet101(pretrained=True)
        # model.set_eval()
        # predict_single_tlx(model, image_file)
        #
        # model = resnet152(pretrained=True)
        # model.set_eval()
        # predict_single_tlx(model, image_file)
```

**Comment by qiutzh** [comment]
@Laicheng0830 忘记回复您了，抱歉，嵌套结构的网络定义tensorlayerx也是支持的~
