### ISSUE TITLE
DataLoader()报错，0.5.6可以正常训练，最新版本会报错，报错如下：

### ISSUE THREAD

**Issue by Eric-yuye** [tensorlayer/TensorLayerX#43]
Traceback (most recent call last):
  File "D:/sthq/code/tensorlayerX/train_vision.py", line 136, in <module>
    train_tlx('fastfcn')
  File "D:/sthq/code/tensorlayerX/train_vision.py", line 123, in train_tlx
    to_static_training=cfg.to_static_training
  File "D:\sthq\code\tensorlayerX\tlx_models\core\train.py", line 146, in train
    for i in loader:
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\tensorlayerx\dataflow\utils.py", line 417, in __next__
    data = self._next_data()
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\tensorlayerx\dataflow\utils.py", line 438, in _next_data
    data = self._dataset_fetcher.fetch(index)
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\tensorlayerx\dataflow\utils.py", line 350, in fetch
    return self.collate_fn(data)
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\tensorlayerx\dataflow\utils.py", line 308, in default_collate
    return default_collate_paddle(batch)
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\tensorlayerx\dataflow\utils.py", line 184, in default_collate_paddle
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\tensorlayerx\dataflow\utils.py", line 184, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\tensorlayerx\dataflow\utils.py", line 308, in default_collate
    return default_collate_paddle(batch)
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\tensorlayerx\dataflow\utils.py", line 173, in default_collate_paddle
    return default_collate([paddle.to_tensor(b) for b in batch])
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\tensorlayerx\dataflow\utils.py", line 308, in default_collate
    return default_collate_paddle(batch)
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\tensorlayerx\dataflow\utils.py", line 165, in default_collate_paddle
    return paddle.stack(batch, 0)
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\paddle\tensor\manipulation.py", line 903, in stack
    return layers.stack(x, axis, name)
  File "F:\anaconda\envs\tensorlayerX\lib\site-packages\paddle\fluid\layers\nn.py", line 10397, in stack
    return _C_ops.stack(x, 'axis', axis)
RuntimeError: (NotFound) Operator stack does not have kernel for data_type[uint8_t]:data_layout[Undefined(AnyLayout)]:place[Place(cpu)]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at C:\home\workspace\Paddle_release\paddle\fluid\imperative\prepared_operator.cc:403)
  [operator < stack > error]

进程已结束，退出代码 1

**Comment by hanjr92** [comment]
Operator stack does not have kernel for data_type[uint8_t]: 你两次读取的数据是一样的么，我看到这边报错是paddle 自己的算子不支持 uint8_t格式
